server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.11.128
    virtual-host: /leyou
    username: leyou
    password: leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

ly:
  static:
    itemDir: C:/hm70/tools/nginx-1.12.2/html/item
    itemTemplate: item