server:
  port: 10010

spring:
  application:
    name: api-gateway
  redis:
    host: 192.168.11.128


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka


zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    upload-service: /upload/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service:
      path: /order/**
      serviceId: order-service
      strip-prefix: false
  sensitive-headers:


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms


ribbon:
  ConnectTimeout: 500 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试



ly:
  cors:
    allowedOrigins:
      - http://manage.leyou.com
      - http://www.leyou.com
    allowCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 3600
    filterPath: "/**"
  jwt:
    pubKeyPath: D:/heima/rsa/id_rsa.pub # D:/heima/rsa/id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN # cookie名称
    app:
      id: 7 # 服务id
      secret: ${spring.application.name} # 服务密钥，默认是服务的名称
      headerName: privilege_header
  filter:
    allowPaths:
      - /api/auth/login
      - /api/auth/verify
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
